services:
  flask:
    container_name: flask
    build: ./app
    networks:
      - labnet
    deploy:
      resources:
        limits:
          memory: 4G
    #       cpus: '0.25'
    expose:
      - "80"
  nginx:
    container_name: nginx
    image: nginx:stable
    depends_on:
      - flask
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/log:/var/log/nginx
      - ./nginx/static:/var/www/static:ro
    networks:
      - labnet
    ports:
      - "80:80"
  netdata:
    image: netdata/netdata
    container_name: netdata
    pid: host
    network_mode: host
    restart: unless-stopped
    environment:
      - DO_NOT_TRACK=1
      - DISABLE_TELEMETRY=1
      - NETDATA_DISABLE_CLOUD=1
      - NETDATA_REQUIRE_CLOUD=0
    cap_add:
      - SYS_PTRACE
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    volumes:
      - ./netdata:/etc/netdata
      - netdatalib:/var/lib/netdata
      - netdatacache:/var/cache/netdata
      - ./nginx/log:/var/log/nginx
      - /:/host/root:ro,rslave
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /etc/localtime:/etc/localtime:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro
      - /var/log:/host/var/log:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /run/dbus:/run/dbus:ro
    depends_on:
      - nginx

volumes:
  netdataconfig:
  netdatalib:
  netdatacache:

networks:
  labnet:
    driver: bridge
